### PR TITLE
added implementation examples to version 2023.1

### PR DESCRIPTION
**Pull request by enikao**

### CODE REVIEW

**Comment by enikao** [comment]
@dslmeinte @joswarmer Please update the repo / npm URLs for TypeScript and Freon

**Comment by dslmeinte** [comment]
> @dslmeinte @joswarmer Please update the repo / npm URLs for TypeScript and Freon

Repo link for TS is correct. But I guess it also makes sense to add links to the packages on `npmjs`?

**Comment by enikao** [comment]
> Repo link for TS is correct. But I guess it also makes sense to add links to the packages on `npmjs`?

Definitely. And maybe have a more specific (and stable) link for the repo? In lw-mps, I created tags for the release.

**Comment by joswarmer** [comment]
Link to freon repo is ok,  I have not done a release yet, but can do that if needed.  I then also need to release Freon itself as lioncore-freon is using a beta version. of Freon.

**Comment by joswarmer** [comment]
I can release this this weekend, if that is fast enough.

**Comment by dslmeinte** [comment]
> > Repo link for TS is correct. But I guess it also makes sense to add links to the packages on `npmjs`?
> 
> Definitely. And maybe have a more specific (and stable) link for the repo? In lw-mps, I created tags for the release.

I can do that as soon as we've released (version: 0.5.0).

**Review by dslmeinte — APPROVED** [review]

**Comment by enikao** [comment]
I guess we can wait at least for Freon, maybe also for TS.

**Review by joswarmer — APPROVED** [review]

**Comment by enikao** [comment]
@joswarmer You don't want to update the links to Freon?

**Pull request merged**
