### PR TITLE
Niko/langdev presentation

### PR DESCRIPTION
**Pull request by enikao**

### CODE REVIEW

**Comment by enikao** [comment]
**TODO: Merge with squash**

**Comment by dslmeinte** [comment]
> **TODO: Merge with squash**

After all, Halloween is over so we can repurpose all the pumpkins 😁

**Comment by dslmeinte** [comment]
Slide 16 of the LANGDEV talk deck has a couple of occurrences of "L**I**onWeb".

**Comment by joswarmer** [comment]
> Slide 16 of the LANGDEV talk deck has a couple of occurrences of "L**I**onWeb".

Changed them, but we will not be using this slide either.

**Pull request merged**
